### PR TITLE
updated GENeSYS-MOD linkages script to model version 3.1

### PR DESCRIPTION
**Pull request by loeffko**
added the new data processing workflow for the current versions of GENeSYS-MOD
also updated the documentation to be clear in the use

added definitions from the openENTRANCE repo to offer a baseline for new users, but added a disclaimer that new definitions should be downloaded for proper use of the script

### CODE REVIEW

**Review by danielhuppmann — CHANGES_REQUESTED** [review]
It's probably a mistake to commit the "definitions" and "mappings" folders to this repository, right?

**Comment by loeffko** [comment]
This was actually on purpose, so people could use the downloaded version and have a guaranteed working version.
But if you feel like this should not be the case (to be forced to always have to download the most current definitions and mappings), I can remove them.
It is anyhow included in the documentation where to find them.

**Comment by danielhuppmann** [comment]
Then let's do a proper release of the nomenclature and you refer to that release version, or you simply refer to the commit hash - that's unique and does not require duplication of information (which too often leads to confusion or problems down the line).

**Comment by loeffko** [comment]
@danielhuppmann removed definitions from distribution, now names commit [e16defbd61ad865eb98c2fc718122f10b4c7341e ](https://github.com/openENTRANCE/openentrance/commit/e16defbd61ad865eb98c2fc718122f10b4c7341e) to be confirmed stable

also expanded documentation a slight bit and changes a pandas function that would give warnings if the most current pandas version had been used

**Review by danielhuppmann — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
